### ISSUE TITLE
Split library into modules

### ISSUE THREAD

**Issue by mycognosist** [sunrise-choir/ssb-validate#6]
Following the addition of batch validation methods to support multi-author and out-of-order use cases, along with many unit tests and test messages, `src/lib.rs` has become very large (like...1525 lines large 0_0...that's my bad). It would be easier to navigate and reason about the code if it were split into modules.

I'm not entirely sure about the best split. Perhaps something like this:

`src/lib.rs`
`src/message.rs`
`src/message_value.rs`
`src/error.rs`
`src/test_data.rs`

`src/message.rs` would contain all `*_message_hash_chain*` functions.

`src/message_value.rs` would contain all `*_message_value_hash_chain*` functions.

**Comment by staltz** [comment]
> Perhaps something like this:
> 
> `src/lib.rs`
> `src/message.rs`
> `src/message_value.rs`
> `src/error.rs`
> `src/test_data.rs`
> 
> `src/message.rs` would contain all `*_message_hash_chain*` functions.
> 
> `src/message_value.rs` would contain all `*_message_value_hash_chain*` functions.

Yep, I fully agree. I took a look at `src/lib.rs` and my intuition was to do the split like that too.

**Comment by mycognosist** [comment]
Rad, thanks for taking a look! I'll probably also move the helper functions into `src/utils.rs`:

`multihash_from_bytes`
`is_correct_order`
`is_canonical_base64`
etc.

**Comment by mycognosist** [comment]
Merged in PR https://github.com/sunrise-choir/ssb-validate/pull/7
